### ISSUE TITLE
加多这个

### ISSUE THREAD

**Issue by InfiBatnis** [killop/anything_about_game#6]
DOTS
https://github.com/Antypodish/Unity_DOTS_NodePathFinding
https://github.com/sebas77/Svelto.MiniExamples   (Svelto.ECS 是他们自己开发的，也可以整合Unity.ECS,也有提到支持Job 和 burst,还有其他的...)

**Comment by killop** [comment]
已经添加

**Comment by InfiBatnis** [comment]
OK
